SELECT MONTH(START_DATE) AS MONTH
     , CAR_ID
     , COUNT(CAR_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE YEAR(START_DATE) = '2022'
   AND MONTH(START_DATE) BETWEEN 8 AND 10
   AND CAR_ID IN(
    select CAR_ID
      from CAR_RENTAL_COMPANY_RENTAL_HISTORY
     where YEAR(START_DATE) = '2022' AND MONTH(START_DATE) BETWEEN 8 AND 10
     group by CAR_ID
     having count(*) > 4
   )
 GROUP BY MONTH,CAR_ID
 order by MONTH,CAR_ID desc;